export const COMIENZA_DESCARGA_TAREAS = 'COMIENZA_DESCARGA_TAREAS';
export const DESCARGA_TAREAS_EXITO = 'DESCARGA_TAREAS_EXITO';
export const DESCARGA_TAREAS_ERROR = 'DESCARGA_TAREAS_ERROR';

export const COMIENZA_AGREGAR_TAREA = 'COMIENZA_AGREGAR_TAREA';
export const AGREGAR_TAREA_EXITO = 'AGREGAR_TAREA_EXITO';
export const AGREGAR_TAREA_ERROR = 'VALIDAR_TAREA_ERROR';

export const COMIENZA_EDITAR_TAREA = 'EDITAR_TAREA';
export const SET_TAREA_EDITAR = 'SET_TAREA_EDITAR';
export const EDITAR_TAREA_EXITO = 'EDITAR_TAREA_EXITO';
export const EDITAR_TAREA_ERROR = 'EDITAR_TAREA_ERROR';

export const COMIENZA_ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const ELIMINAR_TAREA_EXITO = 'ELIMINAR_TAREA_EXITO';
export const ELIMINAR_TAREA_ERROR = 'ELIMINAR_TAREA_ERROR';

export const VALIDAR_TAREA = 'VALIDAR_TAREA';

export const MOSTRAR_MODAL = 'MOSTRAR_MODAL';
export const OCULTAR_MODAL = 'OCULTAR_MODAL';